name: e2e tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  dry-run-test-2: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Pantela996/stale@main
        id: stale
        with:
          stale-issue-message: 'This issue is stale'
          stale-pr-message: 'This PR is stale'
          debug-only: true
          labels-to-add-when-stale: 'test'
      - name: Print outputs
        run: echo ${{ format('{0},{1}', toJSON(steps.stale.outputs.staled-issues-prs), toJSON(steps.stale.outputs.closed-issues-prs)) }}
